<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/models/sailboat.glb --types --shadows --suspense
-->

<script lang='ts'>
    import type * as THREE from 'three'
    import { Group } from 'three'
    import { T } from '@threlte/core'
    import { useGltf, useSuspense } from '@threlte/extras'
    import { AutoColliders } from '@threlte/rapier';

    export const ref = new Group()

    const suspend = useSuspense()

    type GLTFResult = {
        nodes: {
        Cover_Hull: THREE.Mesh
        Left_Solar_Panel: THREE.Mesh
        Outer_Hull: THREE.Mesh
        Right_Solar_Panel: THREE.Mesh
        Sails: THREE.Mesh
        Wires: THREE.Mesh
        }
        materials: {
        ['lambert15SG.001']: THREE.MeshStandardMaterial
        ['SolarPanelMaterial.001']: THREE.MeshStandardMaterial
        SolarPanelMaterial: THREE.MeshStandardMaterial
        ['lambert16SG.001']: THREE.MeshStandardMaterial
        }
    }

    const gltf = suspend(useGltf<GLTFResult>('/models/sailboat.glb'))

</script>

<T is={ref} {...$$restProps}>
    {#await gltf}
        <slot name='fallback' />
    {:then gltf}
        <AutoColliders shape={'convexHull'}>
            <T.Mesh
                castShadow
                receiveShadow
                geometry={gltf.nodes.Cover_Hull.geometry}
                material={gltf.materials['lambert15SG.001']}
            />
            <T.Mesh
                castShadow
                receiveShadow
                geometry={gltf.nodes.Left_Solar_Panel.geometry}
                material={gltf.materials['SolarPanelMaterial.001']}
            />
            <T.Mesh
                castShadow
                receiveShadow
                geometry={gltf.nodes.Outer_Hull.geometry}
                material={gltf.materials['lambert15SG.001']}
            />
            <T.Mesh
                castShadow
                receiveShadow
                geometry={gltf.nodes.Right_Solar_Panel.geometry}
                material={gltf.materials.SolarPanelMaterial}
            />
            <T.Mesh
                castShadow
                receiveShadow
                geometry={gltf.nodes.Sails.geometry}
                material={gltf.materials['lambert16SG.001']}
            />
            <T.Mesh
                castShadow
                receiveShadow
                geometry={gltf.nodes.Wires.geometry}
                material={gltf.materials['lambert15SG.001']}
            />
        </AutoColliders>
    {:catch error}
        <slot name='error' {error} />
    {/await}

        <slot {ref} />
</T>